parameters:
#    opltda_entidades.example.class: Opltda\EntidadesBundle\Example

services:
#    opltda_entidades.example:
#        class: %opltda_entidades.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
