opltda_paginas_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: OpltdaPaginasBundle:Default:index }

Autocompleta:
   pattern:  /Autocompleta
   defaults: { _controller: OpltdaPaginasBundle:Default:Autocompleta }  

AutoCompletaCodEnt:
   pattern:  /AutoCompletaCodEnt
   defaults: { _controller: OpltdaPaginasBundle:Default:AutoCompletaCodEnt}  
 
  
combosCadena:
   pattern:  /combosCadena
   defaults: { _controller: OpltdaPaginasBundle:Default:combosCadena}  
  
AutoCadenaCodEnt:
  pattern:  /AutoCadenaCodEnt
  defaults: { _controller: OpltdaPaginasBundle:Default:AutoCadenaCodEnt}  
  
  
auto:
   pattern:  /auto
   defaults: { _controller: OpltdaPaginasBundle:Default:auto }  
  
LoginVista:
    pattern:  /
    defaults: { _controller: OpltdaPaginasBundle:Default:LoginVista }    
        
login:    
   pattern:  /login
   defaults: { _controller: OpltdaPaginasBundle:Default:login }    
   
principal:
    pattern:  /principal
    defaults: { _controller: OpltdaPaginasBundle:Default:principalVista }    
  
pruebaEntidades:
    pattern:  /pruebaEntidades
    defaults: { _controller: OpltdaPaginasBundle:Default:pruebaEntidades }    

listarFocusGroup:
    pattern: /listarFocusGroup
    defaults: {_controller: OpltdaPaginasBundle:Default:listarFocusGroup}
  
listarInversionVial:
    pattern: /listarInversionVial
    defaults: {_controller: OpltdaPaginasBundle:Default:listarInversionVial}
  
  
detallePuerto:
  pattern: /detallePuerto/{id}
  defaults: {_controller: OpltdaPaginasBundle:Default:detallePuerto}
  
listarEntrevista:
    pattern: /listarEntrevista
    defaults: {_controller: OpltdaPaginasBundle:Default:listarEntrevista}
    
listarMapas:
  pattern: /listarMapas
  defaults: {_controller: OpltdaPaginasBundle:Default:listarMapas}
    
    
listarMemoria:
   pattern: /listarMemoria
   defaults: {_controller: OpltdaPaginasBundle:Default:listarMemoria}
   
   
   
listarEstudio:
   pattern: /listarEstudio
   defaults: {_controller: OpltdaPaginasBundle:Default:listarEstudio}

verDetalleEstudio:
    pattern: /verDetalleEstudio/{id}
    defaults: {_controller: OpltdaPaginasBundle:Default:verDetalleEstudio}

listarModelamiento:
    pattern: /listarModelamiento
    defaults: {_controller: OpltdaPaginasBundle:Default:listarModelamiento}
  
